### ISSUE TITLE
Navigation Menu (Mobile)

### ISSUE THREAD

**Issue by zwvr** [zacharyweaver/FridayKnights#3]
**Describe the bug**
Hamburger menu on mobile devices drops down below logo and does not stay up on the top right of the screen.

**To Reproduce**
1. Go to 'https://zacharyweaver.github.io/FridayKnights/' on your mobile device
2. At the top of your screen next to the logo you will should see the menu floating under logo
3. See Error

**Expected behavior**
The designated position should be in the top right corner aligned with logo.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - IPHONE X
 - iOS 12
 - Safari

**Additional context**

**Comment by izulien** [comment]
I assume you mean it does something like below.
![image](https://user-images.githubusercontent.com/14319924/66857066-7f16c200-ef54-11e9-8ede-c6232c35d979.png)

This menu drop also happens on narrow screens (like the Galaxy 5 and iPhone 5).  These are legacy styled devices but are still in the world.  It may be worth checking the width / position rules.

Emulated Galaxy 5
![image](https://user-images.githubusercontent.com/14319924/66857171-b2f1e780-ef54-11e9-9c73-60fa5ddac787.png)

Emulated iPhone 5
![image](https://user-images.githubusercontent.com/14319924/66857199-c00ed680-ef54-11e9-9f25-4c5e2ee0989a.png)

Standard Mobile / expected view
![image](https://user-images.githubusercontent.com/14319924/66857211-cc932f00-ef54-11e9-99b9-0eb534ec4bf6.png)

**Comment by zwvr** [comment]
Fixed in new Update , maybe do away with the hamburger menu since the navigation is currently on the side and with the dots..
