### ISSUE TITLE
Add anchor tags to social and support profiles

### ISSUE THREAD

**Issue by izulien** [zacharyweaver/FridayKnights#5]
Twitter: https://twitter.com/FridayKnights

Patreon: https://www.patreon.com/FridayKnights

Dice Envy: https://FridayKnights.fun/Dice (This is a DNS entry to auto forward to https://diceenvy.com/?rfsn=2712018.0b611b)  If we want this URL to be a landing page on our site we can but the site must be reachable due to existing promos/messaging

**Comment by zwvr** [comment]
**Updated Links**
